# Generated by Django 6.0.2 on 2026-02-23 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('animation_type', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=10)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('text_color', models.CharField(default='#000000', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating_code', 'Generating Code'), ('rendering', 'Rendering Animation'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('code', models.TextField(blank=True, null=True)),
                ('video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='api.chat')),
            ],
        ),
    ]
