# Generated by Django 6.0.2 on 2026-02-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='animation_type',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='text_color',
        ),
    ]
