# Generated by Django 6.0.2 on 2026-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_scene_animation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='scene_references/'),
        ),
    ]
