# Generated by Django 6.0.2 on 2026-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scene_reference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='text_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
