# Generated by Django 6.0.2 on 2026-02-25 03:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scene_text_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='StitchedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Stitched Video', max_length=255)),
                ('video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('source_video_paths', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
