# Generated by Django 6.0.2 on 2026-03-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chat_user_stitchedvideo_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='target_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=50),
        ),
    ]
