# Generated by Django 6.0.2 on 2026-05-04 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_scene_target_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTrainingOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opted_out_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_opt_out', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Training Opt-Out',
                'verbose_name_plural': 'Data Training Opt-Outs',
            },
        ),
    ]
