# Generated by Django 6.0.2 on 2026-05-06 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_data_training_opt_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='manifest',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='source',
            field=models.CharField(choices=[('chat', 'Chat'), ('playground', 'Playground')], default='chat', max_length=20),
        ),
        migrations.CreateModel(
            name='PlaygroundProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Playground', max_length=255)),
                ('graph_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playground_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
