# Generated by Django 6.0.2 on 2026-05-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_scene_manifest_scene_source_playgroundproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='manifest',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='source',
        ),
        migrations.DeleteModel(
            name='PlaygroundProject',
        ),
    ]
